package main

import (
	"fmt"
	"log"
	"pirate-metrics/utils"
	"strconv"
	"sync"
	"time"
)

var BTC_USDT_BINANCE_RATES ConversionRates
var KMD_BTC_BINANCE_RATES ConversionRates
var ETH_BTC_BINANCE_RATES ConversionRates
var DOT_BTC_BINANCE_RATES ConversionRates

func BtcUsdtBinanceAPI(wg *sync.WaitGroup) {
	defer func() {
		if r := recover(); r != nil {
			utils.Log.Println("Recovered in BtcUsdtBinanceAPI", r)
		}
	}()
	updateMarketsAvailable("binance", "BTC-USDT", wg)
	for {
		url := "https://api.binance.com/api/v3/trades?symbol=BTCUSDT"
		params := ``
		result, err := RPCResultMap(url, params)
		if err != nil {
			log.Printf("Got error fetching Binance BTC/USDT rates: %v\n", err)
		}
		// fmt.Println(result)

		resultType := fmt.Sprintf("%T", result)
		if resultType != "[]interface {}" {
			fmt.Println("type is not []interface {}")
			fmt.Println("resultType value:", resultType)
			fmt.Printf("xTyle type: %T\n", resultType)
		} else {
			price, _ := strconv.ParseFloat(result.([]interface{})[0].(map[string]interface{})["price"].(string), 64)
			log.Printf("BTC Price (USDT): %v\n", price)
			var btc ConversionRates
			btc.Timestamp = int64(result.([]interface{})[0].(map[string]interface{})["time"].(float64))
			btc.Base = "USD"
			btc.Market = "Binance"
			btc.Rates.AED = toFixed(FIXER_RATES.Rates.AED*price, 6)
			btc.Rates.AFN = toFixed(FIXER_RATES.Rates.AFN*price, 6)
			btc.Rates.ALL = toFixed(FIXER_RATES.Rates.ALL*price, 6)
			btc.Rates.AMD = toFixed(FIXER_RATES.Rates.AMD*price, 6)
			btc.Rates.ANG = toFixed(FIXER_RATES.Rates.ANG*price, 6)
			btc.Rates.AOA = toFixed(FIXER_RATES.Rates.AOA*price, 6)
			btc.Rates.ARS = toFixed(FIXER_RATES.Rates.ARS*price, 6)
			btc.Rates.AUD = toFixed(FIXER_RATES.Rates.AUD*price, 6)
			btc.Rates.AWG = toFixed(FIXER_RATES.Rates.AWG*price, 6)
			btc.Rates.AZN = toFixed(FIXER_RATES.Rates.AZN*price, 6)
			btc.Rates.BAM = toFixed(FIXER_RATES.Rates.BAM*price, 6)
			btc.Rates.BBD = toFixed(FIXER_RATES.Rates.BBD*price, 6)
			btc.Rates.BDT = toFixed(FIXER_RATES.Rates.BDT*price, 6)
			btc.Rates.BGN = toFixed(FIXER_RATES.Rates.BGN*price, 6)
			btc.Rates.BHD = toFixed(FIXER_RATES.Rates.BHD*price, 6)
			btc.Rates.BIF = toFixed(FIXER_RATES.Rates.BIF*price, 6)
			btc.Rates.BMD = toFixed(FIXER_RATES.Rates.BMD*price, 6)
			btc.Rates.BND = toFixed(FIXER_RATES.Rates.BND*price, 6)
			btc.Rates.BOB = toFixed(FIXER_RATES.Rates.BOB*price, 6)
			btc.Rates.BRL = toFixed(FIXER_RATES.Rates.BRL*price, 6)
			btc.Rates.BSD = toFixed(FIXER_RATES.Rates.BSD*price, 6)
			btc.Rates.BTC = toFixed(FIXER_RATES.Rates.BTC*price, 8)
			btc.Rates.BTN = toFixed(FIXER_RATES.Rates.BTN*price, 6)
			btc.Rates.BWP = toFixed(FIXER_RATES.Rates.BWP*price, 6)
			btc.Rates.BYN = toFixed(FIXER_RATES.Rates.BYN*price, 6)
			btc.Rates.BYR = toFixed(FIXER_RATES.Rates.BYR*price, 6)
			btc.Rates.BZD = toFixed(FIXER_RATES.Rates.BZD*price, 6)
			btc.Rates.CAD = toFixed(FIXER_RATES.Rates.CAD*price, 6)
			btc.Rates.CDF = toFixed(FIXER_RATES.Rates.CDF*price, 6)
			btc.Rates.CHF = toFixed(FIXER_RATES.Rates.CHF*price, 6)
			btc.Rates.CLF = toFixed(FIXER_RATES.Rates.CLF*price, 6)
			btc.Rates.CLP = toFixed(FIXER_RATES.Rates.CLP*price, 6)
			btc.Rates.CNY = toFixed(FIXER_RATES.Rates.CNY*price, 6)
			btc.Rates.COP = toFixed(FIXER_RATES.Rates.COP*price, 6)
			btc.Rates.CRC = toFixed(FIXER_RATES.Rates.CRC*price, 6)
			btc.Rates.CUC = toFixed(FIXER_RATES.Rates.CUC*price, 6)
			btc.Rates.CUP = toFixed(FIXER_RATES.Rates.CUP*price, 6)
			btc.Rates.CVE = toFixed(FIXER_RATES.Rates.CVE*price, 6)
			btc.Rates.CZK = toFixed(FIXER_RATES.Rates.CZK*price, 6)
			btc.Rates.DJF = toFixed(FIXER_RATES.Rates.DJF*price, 6)
			btc.Rates.DKK = toFixed(FIXER_RATES.Rates.DKK*price, 6)
			btc.Rates.DOP = toFixed(FIXER_RATES.Rates.DOP*price, 6)
			btc.Rates.DZD = toFixed(FIXER_RATES.Rates.DZD*price, 6)
			btc.Rates.EGP = toFixed(FIXER_RATES.Rates.EGP*price, 6)
			btc.Rates.ERN = toFixed(FIXER_RATES.Rates.ERN*price, 6)
			btc.Rates.ETB = toFixed(FIXER_RATES.Rates.ETB*price, 6)
			btc.Rates.EUR = toFixed(FIXER_RATES.Rates.EUR*price, 6)
			btc.Rates.FJD = toFixed(FIXER_RATES.Rates.FJD*price, 6)
			btc.Rates.FKP = toFixed(FIXER_RATES.Rates.FKP*price, 6)
			btc.Rates.GBP = toFixed(FIXER_RATES.Rates.GBP*price, 6)
			btc.Rates.GEL = toFixed(FIXER_RATES.Rates.GEL*price, 6)
			btc.Rates.GGP = toFixed(FIXER_RATES.Rates.GGP*price, 6)
			btc.Rates.GHS = toFixed(FIXER_RATES.Rates.GHS*price, 6)
			btc.Rates.GIP = toFixed(FIXER_RATES.Rates.GIP*price, 6)
			btc.Rates.GMD = toFixed(FIXER_RATES.Rates.GMD*price, 6)
			btc.Rates.GNF = toFixed(FIXER_RATES.Rates.GNF*price, 6)
			btc.Rates.GTQ = toFixed(FIXER_RATES.Rates.GTQ*price, 6)
			btc.Rates.GYD = toFixed(FIXER_RATES.Rates.GYD*price, 6)
			btc.Rates.HKD = toFixed(FIXER_RATES.Rates.HKD*price, 6)
			btc.Rates.HNL = toFixed(FIXER_RATES.Rates.HNL*price, 6)
			btc.Rates.HRK = toFixed(FIXER_RATES.Rates.HRK*price, 6)
			btc.Rates.HTG = toFixed(FIXER_RATES.Rates.HTG*price, 6)
			btc.Rates.HUF = toFixed(FIXER_RATES.Rates.HUF*price, 6)
			btc.Rates.IDR = toFixed(FIXER_RATES.Rates.IDR*price, 6)
			btc.Rates.ILS = toFixed(FIXER_RATES.Rates.ILS*price, 6)
			btc.Rates.IMP = toFixed(FIXER_RATES.Rates.IMP*price, 6)
			btc.Rates.INR = toFixed(FIXER_RATES.Rates.INR*price, 6)
			btc.Rates.IQD = toFixed(FIXER_RATES.Rates.IQD*price, 6)
			btc.Rates.IRR = toFixed(FIXER_RATES.Rates.IRR*price, 6)
			btc.Rates.ISK = toFixed(FIXER_RATES.Rates.ISK*price, 6)
			btc.Rates.JEP = toFixed(FIXER_RATES.Rates.JEP*price, 6)
			btc.Rates.JMD = toFixed(FIXER_RATES.Rates.JMD*price, 6)
			btc.Rates.JOD = toFixed(FIXER_RATES.Rates.JOD*price, 6)
			btc.Rates.JPY = toFixed(FIXER_RATES.Rates.JPY*price, 6)
			btc.Rates.KES = toFixed(FIXER_RATES.Rates.KES*price, 6)
			btc.Rates.KGS = toFixed(FIXER_RATES.Rates.KGS*price, 6)
			btc.Rates.KHR = toFixed(FIXER_RATES.Rates.KHR*price, 6)
			btc.Rates.KMF = toFixed(FIXER_RATES.Rates.KMF*price, 6)
			btc.Rates.KPW = toFixed(FIXER_RATES.Rates.KPW*price, 6)
			btc.Rates.KRW = toFixed(FIXER_RATES.Rates.KRW*price, 6)
			btc.Rates.KWD = toFixed(FIXER_RATES.Rates.KWD*price, 6)
			btc.Rates.KYD = toFixed(FIXER_RATES.Rates.KYD*price, 6)
			btc.Rates.KZT = toFixed(FIXER_RATES.Rates.KZT*price, 6)
			btc.Rates.LAK = toFixed(FIXER_RATES.Rates.LAK*price, 6)
			btc.Rates.LBP = toFixed(FIXER_RATES.Rates.LBP*price, 6)
			btc.Rates.LKR = toFixed(FIXER_RATES.Rates.LKR*price, 6)
			btc.Rates.LRD = toFixed(FIXER_RATES.Rates.LRD*price, 6)
			btc.Rates.LSL = toFixed(FIXER_RATES.Rates.LSL*price, 6)
			btc.Rates.LTL = toFixed(FIXER_RATES.Rates.LTL*price, 6)
			btc.Rates.LVL = toFixed(FIXER_RATES.Rates.LVL*price, 6)
			btc.Rates.LYD = toFixed(FIXER_RATES.Rates.LYD*price, 6)
			btc.Rates.MAD = toFixed(FIXER_RATES.Rates.MAD*price, 6)
			btc.Rates.MDL = toFixed(FIXER_RATES.Rates.MDL*price, 6)
			btc.Rates.MGA = toFixed(FIXER_RATES.Rates.MGA*price, 6)
			btc.Rates.MKD = toFixed(FIXER_RATES.Rates.MKD*price, 6)
			btc.Rates.MMK = toFixed(FIXER_RATES.Rates.MMK*price, 6)
			btc.Rates.MNT = toFixed(FIXER_RATES.Rates.MNT*price, 6)
			btc.Rates.MOP = toFixed(FIXER_RATES.Rates.MOP*price, 6)
			btc.Rates.MRO = toFixed(FIXER_RATES.Rates.MRO*price, 6)
			btc.Rates.MUR = toFixed(FIXER_RATES.Rates.MUR*price, 6)
			btc.Rates.MVR = toFixed(FIXER_RATES.Rates.MVR*price, 6)
			btc.Rates.MWK = toFixed(FIXER_RATES.Rates.MWK*price, 6)
			btc.Rates.MXN = toFixed(FIXER_RATES.Rates.MXN*price, 6)
			btc.Rates.MYR = toFixed(FIXER_RATES.Rates.MYR*price, 6)
			btc.Rates.MZN = toFixed(FIXER_RATES.Rates.MZN*price, 6)
			btc.Rates.NAD = toFixed(FIXER_RATES.Rates.NAD*price, 6)
			btc.Rates.NGN = toFixed(FIXER_RATES.Rates.NGN*price, 6)
			btc.Rates.NIO = toFixed(FIXER_RATES.Rates.NIO*price, 6)
			btc.Rates.NOK = toFixed(FIXER_RATES.Rates.NOK*price, 6)
			btc.Rates.NPR = toFixed(FIXER_RATES.Rates.NPR*price, 6)
			btc.Rates.NZD = toFixed(FIXER_RATES.Rates.NZD*price, 6)
			btc.Rates.OMR = toFixed(FIXER_RATES.Rates.OMR*price, 6)
			btc.Rates.PAB = toFixed(FIXER_RATES.Rates.PAB*price, 6)
			btc.Rates.PEN = toFixed(FIXER_RATES.Rates.PEN*price, 6)
			btc.Rates.PGK = toFixed(FIXER_RATES.Rates.PGK*price, 6)
			btc.Rates.PHP = toFixed(FIXER_RATES.Rates.PHP*price, 6)
			btc.Rates.PKR = toFixed(FIXER_RATES.Rates.PKR*price, 6)
			btc.Rates.PLN = toFixed(FIXER_RATES.Rates.PLN*price, 6)
			btc.Rates.PYG = toFixed(FIXER_RATES.Rates.PYG*price, 6)
			btc.Rates.QAR = toFixed(FIXER_RATES.Rates.QAR*price, 6)
			btc.Rates.RON = toFixed(FIXER_RATES.Rates.RON*price, 6)
			btc.Rates.RSD = toFixed(FIXER_RATES.Rates.RSD*price, 6)
			btc.Rates.RUB = toFixed(FIXER_RATES.Rates.RUB*price, 6)
			btc.Rates.RWF = toFixed(FIXER_RATES.Rates.RWF*price, 6)
			btc.Rates.SAR = toFixed(FIXER_RATES.Rates.SAR*price, 6)
			btc.Rates.SBD = toFixed(FIXER_RATES.Rates.SBD*price, 6)
			btc.Rates.SCR = toFixed(FIXER_RATES.Rates.SCR*price, 6)
			btc.Rates.SDG = toFixed(FIXER_RATES.Rates.SDG*price, 6)
			btc.Rates.SEK = toFixed(FIXER_RATES.Rates.SEK*price, 6)
			btc.Rates.SGD = toFixed(FIXER_RATES.Rates.SGD*price, 6)
			btc.Rates.SHP = toFixed(FIXER_RATES.Rates.SHP*price, 6)
			btc.Rates.SLL = toFixed(FIXER_RATES.Rates.SLL*price, 6)
			btc.Rates.SOS = toFixed(FIXER_RATES.Rates.SOS*price, 6)
			btc.Rates.SRD = toFixed(FIXER_RATES.Rates.SRD*price, 6)
			btc.Rates.STD = toFixed(FIXER_RATES.Rates.STD*price, 6)
			btc.Rates.SVC = toFixed(FIXER_RATES.Rates.SVC*price, 6)
			btc.Rates.SYP = toFixed(FIXER_RATES.Rates.SYP*price, 6)
			btc.Rates.SZL = toFixed(FIXER_RATES.Rates.SZL*price, 6)
			btc.Rates.THB = toFixed(FIXER_RATES.Rates.THB*price, 6)
			btc.Rates.TJS = toFixed(FIXER_RATES.Rates.TJS*price, 6)
			btc.Rates.TMT = toFixed(FIXER_RATES.Rates.TMT*price, 6)
			btc.Rates.TND = toFixed(FIXER_RATES.Rates.TND*price, 6)
			btc.Rates.TOP = toFixed(FIXER_RATES.Rates.TOP*price, 6)
			btc.Rates.TRY = toFixed(FIXER_RATES.Rates.TRY*price, 6)
			btc.Rates.TTD = toFixed(FIXER_RATES.Rates.TTD*price, 6)
			btc.Rates.TWD = toFixed(FIXER_RATES.Rates.TWD*price, 6)
			btc.Rates.TZS = toFixed(FIXER_RATES.Rates.TZS*price, 6)
			btc.Rates.UAH = toFixed(FIXER_RATES.Rates.UAH*price, 6)
			btc.Rates.UGX = toFixed(FIXER_RATES.Rates.UGX*price, 6)
			btc.Rates.USD = toFixed(FIXER_RATES.Rates.USD*price, 6)
			btc.Rates.UYU = toFixed(FIXER_RATES.Rates.UYU*price, 6)
			btc.Rates.UZS = toFixed(FIXER_RATES.Rates.UZS*price, 6)
			btc.Rates.VEF = toFixed(FIXER_RATES.Rates.VEF*price, 6)
			btc.Rates.VND = toFixed(FIXER_RATES.Rates.VND*price, 6)
			btc.Rates.VUV = toFixed(FIXER_RATES.Rates.VUV*price, 6)
			btc.Rates.WST = toFixed(FIXER_RATES.Rates.WST*price, 6)
			btc.Rates.XAF = toFixed(FIXER_RATES.Rates.XAF*price, 6)
			btc.Rates.XAG = toFixed(FIXER_RATES.Rates.XAG*price, 6)
			btc.Rates.XAU = toFixed(FIXER_RATES.Rates.XAU*price, 6)
			btc.Rates.XCD = toFixed(FIXER_RATES.Rates.XCD*price, 6)
			btc.Rates.XDR = toFixed(FIXER_RATES.Rates.XDR*price, 6)
			btc.Rates.XOF = toFixed(FIXER_RATES.Rates.XOF*price, 6)
			btc.Rates.XPF = toFixed(FIXER_RATES.Rates.XPF*price, 6)
			btc.Rates.YER = toFixed(FIXER_RATES.Rates.YER*price, 6)
			btc.Rates.ZAR = toFixed(FIXER_RATES.Rates.ZAR*price, 6)
			btc.Rates.ZMK = toFixed(FIXER_RATES.Rates.ZMK*price, 6)
			btc.Rates.ZMW = toFixed(FIXER_RATES.Rates.ZMW*price, 6)
			btc.Rates.ZWL = toFixed(FIXER_RATES.Rates.ZWL*price, 6)

			BTC_USDT_BINANCE_RATES = btc
			if BTC_PRICE_SOURCE == "Binance" {
				BTC_RATES = btc
			}

			// b, _ := json.Marshal(arrr)
			// fmt.Println(string(b))
		}

		sleepSeconds := BINANCE_SECONDS
		log.Printf("Updated BTC Rates from Binance for BTC/USDT pair. Will update again in %v seconds...\n", sleepSeconds)
		time.Sleep(time.Duration(sleepSeconds) * time.Second)
	}
}

func KmdBtcBinanceAPI(wg *sync.WaitGroup) {
	defer func() {
		if r := recover(); r != nil {
			utils.Log.Println("Recovered in KmdBtcBinanceAPI", r)
		}
	}()
	updateMarketsAvailable("binance", "KMD-BTC", wg)
	// Forever loop to keep fetching rates every N seconds
	for {
		url := "https://api.binance.com/api/v3/trades?symbol=KMDBTC"
		params := ``
		result, err := RPCResultMap(url, params)
		if err != nil {
			log.Printf("Got error fetching Binance KMD/BTC rates: %v\n", err)
		}
		// fmt.Println(result)

		resultType := fmt.Sprintf("%T", result)
		if resultType != "[]interface {}" {
			fmt.Println("type is not []interface {}")
			fmt.Println("resultType value:", resultType)
			fmt.Printf("xTyle type: %T\n", resultType)
		} else {
			kmdBtcPrice, _ := strconv.ParseFloat(result.([]interface{})[0].(map[string]interface{})["price"].(string), 64)
			kmdUSDPrice := kmdBtcPrice * BTC_RATES.Rates.USD
			// fmt.Println("==========================")
			// fmt.Printf("KMD Price (BTC): %.8f\n", kmdBtcPrice)
			// fmt.Printf("KMD Price (USD): %.6f\n", kmdUSDPrice)
			// fmt.Println("==========================")
			var kmd ConversionRates
			kmd.Timestamp = int64(result.([]interface{})[0].(map[string]interface{})["time"].(float64))
			kmd.Base = "KMD/BTC"
			kmd.Market = "Binance"
			kmd.Rates.AED = toFixed(FIXER_RATES.Rates.AED*kmdBtcPrice, 6)
			kmd.Rates.AFN = toFixed(FIXER_RATES.Rates.AFN*kmdBtcPrice, 6)
			kmd.Rates.ALL = toFixed(FIXER_RATES.Rates.ALL*kmdBtcPrice, 6)
			kmd.Rates.AMD = toFixed(FIXER_RATES.Rates.AMD*kmdBtcPrice, 6)
			kmd.Rates.ANG = toFixed(FIXER_RATES.Rates.ANG*kmdBtcPrice, 6)
			kmd.Rates.AOA = toFixed(FIXER_RATES.Rates.AOA*kmdBtcPrice, 6)
			kmd.Rates.ARS = toFixed(FIXER_RATES.Rates.ARS*kmdBtcPrice, 6)
			kmd.Rates.AUD = toFixed(FIXER_RATES.Rates.AUD*kmdBtcPrice, 6)
			kmd.Rates.AWG = toFixed(FIXER_RATES.Rates.AWG*kmdBtcPrice, 6)
			kmd.Rates.AZN = toFixed(FIXER_RATES.Rates.AZN*kmdBtcPrice, 6)
			kmd.Rates.BAM = toFixed(FIXER_RATES.Rates.BAM*kmdBtcPrice, 6)
			kmd.Rates.BBD = toFixed(FIXER_RATES.Rates.BBD*kmdBtcPrice, 6)
			kmd.Rates.BDT = toFixed(FIXER_RATES.Rates.BDT*kmdBtcPrice, 6)
			kmd.Rates.BGN = toFixed(FIXER_RATES.Rates.BGN*kmdBtcPrice, 6)
			kmd.Rates.BHD = toFixed(FIXER_RATES.Rates.BHD*kmdBtcPrice, 6)
			kmd.Rates.BIF = toFixed(FIXER_RATES.Rates.BIF*kmdBtcPrice, 6)
			kmd.Rates.BMD = toFixed(kmdUSDPrice, 6)
			kmd.Rates.BND = toFixed(FIXER_RATES.Rates.BND*kmdBtcPrice, 6)
			kmd.Rates.BOB = toFixed(FIXER_RATES.Rates.BOB*kmdBtcPrice, 6)
			kmd.Rates.BRL = toFixed(FIXER_RATES.Rates.BRL*kmdBtcPrice, 6)
			kmd.Rates.BSD = toFixed(FIXER_RATES.Rates.BSD*kmdBtcPrice, 6)
			kmd.Rates.BTC = toFixed(kmdBtcPrice, 8)
			kmd.Rates.BTN = toFixed(FIXER_RATES.Rates.BTN*kmdBtcPrice, 6)
			kmd.Rates.BWP = toFixed(FIXER_RATES.Rates.BWP*kmdBtcPrice, 6)
			kmd.Rates.BYN = toFixed(FIXER_RATES.Rates.BYN*kmdBtcPrice, 6)
			kmd.Rates.BYR = toFixed(FIXER_RATES.Rates.BYR*kmdBtcPrice, 6)
			kmd.Rates.BZD = toFixed(FIXER_RATES.Rates.BZD*kmdBtcPrice, 6)
			kmd.Rates.CAD = toFixed(FIXER_RATES.Rates.CAD*kmdBtcPrice, 6)
			kmd.Rates.CDF = toFixed(FIXER_RATES.Rates.CDF*kmdBtcPrice, 6)
			kmd.Rates.CHF = toFixed(FIXER_RATES.Rates.CHF*kmdBtcPrice, 6)
			kmd.Rates.CLF = toFixed(FIXER_RATES.Rates.CLF*kmdBtcPrice, 6)
			kmd.Rates.CLP = toFixed(FIXER_RATES.Rates.CLP*kmdBtcPrice, 6)
			kmd.Rates.CNY = toFixed(FIXER_RATES.Rates.CNY*kmdBtcPrice, 6)
			kmd.Rates.COP = toFixed(FIXER_RATES.Rates.COP*kmdBtcPrice, 6)
			kmd.Rates.CRC = toFixed(FIXER_RATES.Rates.CRC*kmdBtcPrice, 6)
			kmd.Rates.CUC = toFixed(kmdUSDPrice, 6)
			kmd.Rates.CUP = toFixed(FIXER_RATES.Rates.CUP*kmdBtcPrice, 6)
			kmd.Rates.CVE = toFixed(FIXER_RATES.Rates.CVE*kmdBtcPrice, 6)
			kmd.Rates.CZK = toFixed(FIXER_RATES.Rates.CZK*kmdBtcPrice, 6)
			kmd.Rates.DJF = toFixed(FIXER_RATES.Rates.DJF*kmdBtcPrice, 6)
			kmd.Rates.DKK = toFixed(FIXER_RATES.Rates.DKK*kmdBtcPrice, 6)
			kmd.Rates.DOP = toFixed(FIXER_RATES.Rates.DOP*kmdBtcPrice, 6)
			kmd.Rates.DZD = toFixed(FIXER_RATES.Rates.DZD*kmdBtcPrice, 6)
			kmd.Rates.EGP = toFixed(FIXER_RATES.Rates.EGP*kmdBtcPrice, 6)
			kmd.Rates.ERN = toFixed(FIXER_RATES.Rates.ERN*kmdBtcPrice, 6)
			kmd.Rates.ETB = toFixed(FIXER_RATES.Rates.ETB*kmdBtcPrice, 6)
			kmd.Rates.EUR = toFixed(FIXER_RATES.Rates.EUR*kmdBtcPrice, 6)
			kmd.Rates.FJD = toFixed(FIXER_RATES.Rates.FJD*kmdBtcPrice, 6)
			kmd.Rates.FKP = toFixed(FIXER_RATES.Rates.FKP*kmdBtcPrice, 6)
			kmd.Rates.GBP = toFixed(FIXER_RATES.Rates.GBP*kmdBtcPrice, 6)
			kmd.Rates.GEL = toFixed(FIXER_RATES.Rates.GEL*kmdBtcPrice, 6)
			kmd.Rates.GGP = toFixed(FIXER_RATES.Rates.GGP*kmdBtcPrice, 6)
			kmd.Rates.GHS = toFixed(FIXER_RATES.Rates.GHS*kmdBtcPrice, 6)
			kmd.Rates.GIP = toFixed(FIXER_RATES.Rates.GIP*kmdBtcPrice, 6)
			kmd.Rates.GMD = toFixed(FIXER_RATES.Rates.GMD*kmdBtcPrice, 6)
			kmd.Rates.GNF = toFixed(FIXER_RATES.Rates.GNF*kmdBtcPrice, 6)
			kmd.Rates.GTQ = toFixed(FIXER_RATES.Rates.GTQ*kmdBtcPrice, 6)
			kmd.Rates.GYD = toFixed(FIXER_RATES.Rates.GYD*kmdBtcPrice, 6)
			kmd.Rates.HKD = toFixed(FIXER_RATES.Rates.HKD*kmdBtcPrice, 6)
			kmd.Rates.HNL = toFixed(FIXER_RATES.Rates.HNL*kmdBtcPrice, 6)
			kmd.Rates.HRK = toFixed(FIXER_RATES.Rates.HRK*kmdBtcPrice, 6)
			kmd.Rates.HTG = toFixed(FIXER_RATES.Rates.HTG*kmdBtcPrice, 6)
			kmd.Rates.HUF = toFixed(FIXER_RATES.Rates.HUF*kmdBtcPrice, 6)
			kmd.Rates.IDR = toFixed(FIXER_RATES.Rates.IDR*kmdBtcPrice, 6)
			kmd.Rates.ILS = toFixed(FIXER_RATES.Rates.ILS*kmdBtcPrice, 6)
			kmd.Rates.IMP = toFixed(FIXER_RATES.Rates.IMP*kmdBtcPrice, 6)
			kmd.Rates.INR = toFixed(FIXER_RATES.Rates.INR*kmdBtcPrice, 6)
			kmd.Rates.IQD = toFixed(FIXER_RATES.Rates.IQD*kmdBtcPrice, 6)
			kmd.Rates.IRR = toFixed(FIXER_RATES.Rates.IRR*kmdBtcPrice, 6)
			kmd.Rates.ISK = toFixed(FIXER_RATES.Rates.ISK*kmdBtcPrice, 6)
			kmd.Rates.JEP = toFixed(FIXER_RATES.Rates.JEP*kmdBtcPrice, 6)
			kmd.Rates.JMD = toFixed(FIXER_RATES.Rates.JMD*kmdBtcPrice, 6)
			kmd.Rates.JOD = toFixed(FIXER_RATES.Rates.JOD*kmdBtcPrice, 6)
			kmd.Rates.JPY = toFixed(FIXER_RATES.Rates.JPY*kmdBtcPrice, 6)
			kmd.Rates.KES = toFixed(FIXER_RATES.Rates.KES*kmdBtcPrice, 6)
			kmd.Rates.KGS = toFixed(FIXER_RATES.Rates.KGS*kmdBtcPrice, 6)
			kmd.Rates.KHR = toFixed(FIXER_RATES.Rates.KHR*kmdBtcPrice, 6)
			kmd.Rates.KMF = toFixed(FIXER_RATES.Rates.KMF*kmdBtcPrice, 6)
			kmd.Rates.KPW = toFixed(FIXER_RATES.Rates.KPW*kmdBtcPrice, 6)
			kmd.Rates.KRW = toFixed(FIXER_RATES.Rates.KRW*kmdBtcPrice, 6)
			kmd.Rates.KWD = toFixed(FIXER_RATES.Rates.KWD*kmdBtcPrice, 6)
			kmd.Rates.KYD = toFixed(FIXER_RATES.Rates.KYD*kmdBtcPrice, 6)
			kmd.Rates.KZT = toFixed(FIXER_RATES.Rates.KZT*kmdBtcPrice, 6)
			kmd.Rates.LAK = toFixed(FIXER_RATES.Rates.LAK*kmdBtcPrice, 6)
			kmd.Rates.LBP = toFixed(FIXER_RATES.Rates.LBP*kmdBtcPrice, 6)
			kmd.Rates.LKR = toFixed(FIXER_RATES.Rates.LKR*kmdBtcPrice, 6)
			kmd.Rates.LRD = toFixed(FIXER_RATES.Rates.LRD*kmdBtcPrice, 6)
			kmd.Rates.LSL = toFixed(FIXER_RATES.Rates.LSL*kmdBtcPrice, 6)
			kmd.Rates.LTL = toFixed(FIXER_RATES.Rates.LTL*kmdBtcPrice, 6)
			kmd.Rates.LVL = toFixed(FIXER_RATES.Rates.LVL*kmdBtcPrice, 6)
			kmd.Rates.LYD = toFixed(FIXER_RATES.Rates.LYD*kmdBtcPrice, 6)
			kmd.Rates.MAD = toFixed(FIXER_RATES.Rates.MAD*kmdBtcPrice, 6)
			kmd.Rates.MDL = toFixed(FIXER_RATES.Rates.MDL*kmdBtcPrice, 6)
			kmd.Rates.MGA = toFixed(FIXER_RATES.Rates.MGA*kmdBtcPrice, 6)
			kmd.Rates.MKD = toFixed(FIXER_RATES.Rates.MKD*kmdBtcPrice, 6)
			kmd.Rates.MMK = toFixed(FIXER_RATES.Rates.MMK*kmdBtcPrice, 6)
			kmd.Rates.MNT = toFixed(FIXER_RATES.Rates.MNT*kmdBtcPrice, 6)
			kmd.Rates.MOP = toFixed(FIXER_RATES.Rates.MOP*kmdBtcPrice, 6)
			kmd.Rates.MRO = toFixed(FIXER_RATES.Rates.MRO*kmdBtcPrice, 6)
			kmd.Rates.MUR = toFixed(FIXER_RATES.Rates.MUR*kmdBtcPrice, 6)
			kmd.Rates.MVR = toFixed(FIXER_RATES.Rates.MVR*kmdBtcPrice, 6)
			kmd.Rates.MWK = toFixed(FIXER_RATES.Rates.MWK*kmdBtcPrice, 6)
			kmd.Rates.MXN = toFixed(FIXER_RATES.Rates.MXN*kmdBtcPrice, 6)
			kmd.Rates.MYR = toFixed(FIXER_RATES.Rates.MYR*kmdBtcPrice, 6)
			kmd.Rates.MZN = toFixed(FIXER_RATES.Rates.MZN*kmdBtcPrice, 6)
			kmd.Rates.NAD = toFixed(FIXER_RATES.Rates.NAD*kmdBtcPrice, 6)
			kmd.Rates.NGN = toFixed(FIXER_RATES.Rates.NGN*kmdBtcPrice, 6)
			kmd.Rates.NIO = toFixed(FIXER_RATES.Rates.NIO*kmdBtcPrice, 6)
			kmd.Rates.NOK = toFixed(FIXER_RATES.Rates.NOK*kmdBtcPrice, 6)
			kmd.Rates.NPR = toFixed(FIXER_RATES.Rates.NPR*kmdBtcPrice, 6)
			kmd.Rates.NZD = toFixed(FIXER_RATES.Rates.NZD*kmdBtcPrice, 6)
			kmd.Rates.OMR = toFixed(FIXER_RATES.Rates.OMR*kmdBtcPrice, 6)
			kmd.Rates.PAB = toFixed(FIXER_RATES.Rates.PAB*kmdBtcPrice, 6)
			kmd.Rates.PEN = toFixed(FIXER_RATES.Rates.PEN*kmdBtcPrice, 6)
			kmd.Rates.PGK = toFixed(FIXER_RATES.Rates.PGK*kmdBtcPrice, 6)
			kmd.Rates.PHP = toFixed(FIXER_RATES.Rates.PHP*kmdBtcPrice, 6)
			kmd.Rates.PKR = toFixed(FIXER_RATES.Rates.PKR*kmdBtcPrice, 6)
			kmd.Rates.PLN = toFixed(FIXER_RATES.Rates.PLN*kmdBtcPrice, 6)
			kmd.Rates.PYG = toFixed(FIXER_RATES.Rates.PYG*kmdBtcPrice, 6)
			kmd.Rates.QAR = toFixed(FIXER_RATES.Rates.QAR*kmdBtcPrice, 6)
			kmd.Rates.RON = toFixed(FIXER_RATES.Rates.RON*kmdBtcPrice, 6)
			kmd.Rates.RSD = toFixed(FIXER_RATES.Rates.RSD*kmdBtcPrice, 6)
			kmd.Rates.RUB = toFixed(FIXER_RATES.Rates.RUB*kmdBtcPrice, 6)
			kmd.Rates.RWF = toFixed(FIXER_RATES.Rates.RWF*kmdBtcPrice, 6)
			kmd.Rates.SAR = toFixed(FIXER_RATES.Rates.SAR*kmdBtcPrice, 6)
			kmd.Rates.SBD = toFixed(FIXER_RATES.Rates.SBD*kmdBtcPrice, 6)
			kmd.Rates.SCR = toFixed(FIXER_RATES.Rates.SCR*kmdBtcPrice, 6)
			kmd.Rates.SDG = toFixed(FIXER_RATES.Rates.SDG*kmdBtcPrice, 6)
			kmd.Rates.SEK = toFixed(FIXER_RATES.Rates.SEK*kmdBtcPrice, 6)
			kmd.Rates.SGD = toFixed(FIXER_RATES.Rates.SGD*kmdBtcPrice, 6)
			kmd.Rates.SHP = toFixed(FIXER_RATES.Rates.SHP*kmdBtcPrice, 6)
			kmd.Rates.SLL = toFixed(FIXER_RATES.Rates.SLL*kmdBtcPrice, 6)
			kmd.Rates.SOS = toFixed(FIXER_RATES.Rates.SOS*kmdBtcPrice, 6)
			kmd.Rates.SRD = toFixed(FIXER_RATES.Rates.SRD*kmdBtcPrice, 6)
			kmd.Rates.STD = toFixed(FIXER_RATES.Rates.STD*kmdBtcPrice, 6)
			kmd.Rates.SVC = toFixed(FIXER_RATES.Rates.SVC*kmdBtcPrice, 6)
			kmd.Rates.SYP = toFixed(FIXER_RATES.Rates.SYP*kmdBtcPrice, 6)
			kmd.Rates.SZL = toFixed(FIXER_RATES.Rates.SZL*kmdBtcPrice, 6)
			kmd.Rates.THB = toFixed(FIXER_RATES.Rates.THB*kmdBtcPrice, 6)
			kmd.Rates.TJS = toFixed(FIXER_RATES.Rates.TJS*kmdBtcPrice, 6)
			kmd.Rates.TMT = toFixed(FIXER_RATES.Rates.TMT*kmdBtcPrice, 6)
			kmd.Rates.TND = toFixed(FIXER_RATES.Rates.TND*kmdBtcPrice, 6)
			kmd.Rates.TOP = toFixed(FIXER_RATES.Rates.TOP*kmdBtcPrice, 6)
			kmd.Rates.TRY = toFixed(FIXER_RATES.Rates.TRY*kmdBtcPrice, 6)
			kmd.Rates.TTD = toFixed(FIXER_RATES.Rates.TTD*kmdBtcPrice, 6)
			kmd.Rates.TWD = toFixed(FIXER_RATES.Rates.TWD*kmdBtcPrice, 6)
			kmd.Rates.TZS = toFixed(FIXER_RATES.Rates.TZS*kmdBtcPrice, 6)
			kmd.Rates.UAH = toFixed(FIXER_RATES.Rates.UAH*kmdBtcPrice, 6)
			kmd.Rates.UGX = toFixed(FIXER_RATES.Rates.UGX*kmdBtcPrice, 6)
			kmd.Rates.USD = toFixed(kmdUSDPrice, 6)
			kmd.Rates.UYU = toFixed(FIXER_RATES.Rates.UYU*kmdBtcPrice, 6)
			kmd.Rates.UZS = toFixed(FIXER_RATES.Rates.UZS*kmdBtcPrice, 6)
			kmd.Rates.VEF = toFixed(FIXER_RATES.Rates.VEF*kmdBtcPrice, 6)
			kmd.Rates.VND = toFixed(FIXER_RATES.Rates.VND*kmdBtcPrice, 6)
			kmd.Rates.VUV = toFixed(FIXER_RATES.Rates.VUV*kmdBtcPrice, 6)
			kmd.Rates.WST = toFixed(FIXER_RATES.Rates.WST*kmdBtcPrice, 6)
			kmd.Rates.XAF = toFixed(FIXER_RATES.Rates.XAF*kmdBtcPrice, 6)
			kmd.Rates.XAG = toFixed(FIXER_RATES.Rates.XAG*kmdBtcPrice, 6)
			kmd.Rates.XAU = toFixed(FIXER_RATES.Rates.XAU*kmdBtcPrice, 6)
			kmd.Rates.XCD = toFixed(FIXER_RATES.Rates.XCD*kmdBtcPrice, 6)
			kmd.Rates.XDR = toFixed(FIXER_RATES.Rates.XDR*kmdBtcPrice, 6)
			kmd.Rates.XOF = toFixed(FIXER_RATES.Rates.XOF*kmdBtcPrice, 6)
			kmd.Rates.XPF = toFixed(FIXER_RATES.Rates.XPF*kmdBtcPrice, 6)
			kmd.Rates.YER = toFixed(FIXER_RATES.Rates.YER*kmdBtcPrice, 6)
			kmd.Rates.ZAR = toFixed(FIXER_RATES.Rates.ZAR*kmdBtcPrice, 6)
			kmd.Rates.ZMK = toFixed(FIXER_RATES.Rates.ZMK*kmdBtcPrice, 6)
			kmd.Rates.ZMW = toFixed(FIXER_RATES.Rates.ZMW*kmdBtcPrice, 6)
			kmd.Rates.ZWL = toFixed(FIXER_RATES.Rates.ZWL*kmdBtcPrice, 6)

			KMD_BTC_BINANCE_RATES = kmd

			// b, _ := json.Marshal(arrr)
			// fmt.Println(string(b))
		}

		sleepSeconds := BINANCE_SECONDS
		log.Printf("Updated KMD Rates from Binance for KMD/BTC pair. Will update again in %v seconds...\n", sleepSeconds)
		time.Sleep(time.Duration(sleepSeconds) * time.Second)
	}
}

func EthBtcBinanceAPI(wg *sync.WaitGroup) {
	defer func() {
		if r := recover(); r != nil {
			utils.Log.Println("Recovered in EthBtcBinanceAPI", r)
		}
	}()
	updateMarketsAvailable("binance", "ETH-BTC", wg)
	// Forever loop to keep fetching rates every N seconds
	for {
		url := "https://api.binance.com/api/v3/trades?symbol=ETHBTC"
		params := ``
		result, err := RPCResultMap(url, params)
		if err != nil {
			log.Printf("Got error fetching Binance ETH/BTC rates: %v\n", err)
		}
		// fmt.Println(result)

		resultType := fmt.Sprintf("%T", result)
		if resultType != "[]interface {}" {
			fmt.Println("type is not []interface {}")
			fmt.Println("resultType value:", resultType)
			fmt.Printf("xTyle type: %T\n", resultType)
		} else {
			ethBtcPrice, _ := strconv.ParseFloat(result.([]interface{})[0].(map[string]interface{})["price"].(string), 64)
			ethUSDPrice := ethBtcPrice * BTC_RATES.Rates.USD
			// fmt.Println("==========================")
			// fmt.Printf("ETH Price (BTC): %.8f\n", ethBtcPrice)
			// fmt.Printf("ETH Price (USD): %.6f\n", ethUSDPrice)
			// fmt.Println("==========================")
			var eth ConversionRates
			eth.Timestamp = int64(result.([]interface{})[0].(map[string]interface{})["time"].(float64))
			eth.Base = "ETH/BTC"
			eth.Market = "Binance"
			eth.Rates.AED = toFixed(FIXER_RATES.Rates.AED*ethBtcPrice, 6)
			eth.Rates.AFN = toFixed(FIXER_RATES.Rates.AFN*ethBtcPrice, 6)
			eth.Rates.ALL = toFixed(FIXER_RATES.Rates.ALL*ethBtcPrice, 6)
			eth.Rates.AMD = toFixed(FIXER_RATES.Rates.AMD*ethBtcPrice, 6)
			eth.Rates.ANG = toFixed(FIXER_RATES.Rates.ANG*ethBtcPrice, 6)
			eth.Rates.AOA = toFixed(FIXER_RATES.Rates.AOA*ethBtcPrice, 6)
			eth.Rates.ARS = toFixed(FIXER_RATES.Rates.ARS*ethBtcPrice, 6)
			eth.Rates.AUD = toFixed(FIXER_RATES.Rates.AUD*ethBtcPrice, 6)
			eth.Rates.AWG = toFixed(FIXER_RATES.Rates.AWG*ethBtcPrice, 6)
			eth.Rates.AZN = toFixed(FIXER_RATES.Rates.AZN*ethBtcPrice, 6)
			eth.Rates.BAM = toFixed(FIXER_RATES.Rates.BAM*ethBtcPrice, 6)
			eth.Rates.BBD = toFixed(FIXER_RATES.Rates.BBD*ethBtcPrice, 6)
			eth.Rates.BDT = toFixed(FIXER_RATES.Rates.BDT*ethBtcPrice, 6)
			eth.Rates.BGN = toFixed(FIXER_RATES.Rates.BGN*ethBtcPrice, 6)
			eth.Rates.BHD = toFixed(FIXER_RATES.Rates.BHD*ethBtcPrice, 6)
			eth.Rates.BIF = toFixed(FIXER_RATES.Rates.BIF*ethBtcPrice, 6)
			eth.Rates.BMD = toFixed(ethUSDPrice, 6)
			eth.Rates.BND = toFixed(FIXER_RATES.Rates.BND*ethBtcPrice, 6)
			eth.Rates.BOB = toFixed(FIXER_RATES.Rates.BOB*ethBtcPrice, 6)
			eth.Rates.BRL = toFixed(FIXER_RATES.Rates.BRL*ethBtcPrice, 6)
			eth.Rates.BSD = toFixed(FIXER_RATES.Rates.BSD*ethBtcPrice, 6)
			eth.Rates.BTC = toFixed(ethBtcPrice, 8)
			eth.Rates.BTN = toFixed(FIXER_RATES.Rates.BTN*ethBtcPrice, 6)
			eth.Rates.BWP = toFixed(FIXER_RATES.Rates.BWP*ethBtcPrice, 6)
			eth.Rates.BYN = toFixed(FIXER_RATES.Rates.BYN*ethBtcPrice, 6)
			eth.Rates.BYR = toFixed(FIXER_RATES.Rates.BYR*ethBtcPrice, 6)
			eth.Rates.BZD = toFixed(FIXER_RATES.Rates.BZD*ethBtcPrice, 6)
			eth.Rates.CAD = toFixed(FIXER_RATES.Rates.CAD*ethBtcPrice, 6)
			eth.Rates.CDF = toFixed(FIXER_RATES.Rates.CDF*ethBtcPrice, 6)
			eth.Rates.CHF = toFixed(FIXER_RATES.Rates.CHF*ethBtcPrice, 6)
			eth.Rates.CLF = toFixed(FIXER_RATES.Rates.CLF*ethBtcPrice, 6)
			eth.Rates.CLP = toFixed(FIXER_RATES.Rates.CLP*ethBtcPrice, 6)
			eth.Rates.CNY = toFixed(FIXER_RATES.Rates.CNY*ethBtcPrice, 6)
			eth.Rates.COP = toFixed(FIXER_RATES.Rates.COP*ethBtcPrice, 6)
			eth.Rates.CRC = toFixed(FIXER_RATES.Rates.CRC*ethBtcPrice, 6)
			eth.Rates.CUC = toFixed(ethUSDPrice, 6)
			eth.Rates.CUP = toFixed(FIXER_RATES.Rates.CUP*ethBtcPrice, 6)
			eth.Rates.CVE = toFixed(FIXER_RATES.Rates.CVE*ethBtcPrice, 6)
			eth.Rates.CZK = toFixed(FIXER_RATES.Rates.CZK*ethBtcPrice, 6)
			eth.Rates.DJF = toFixed(FIXER_RATES.Rates.DJF*ethBtcPrice, 6)
			eth.Rates.DKK = toFixed(FIXER_RATES.Rates.DKK*ethBtcPrice, 6)
			eth.Rates.DOP = toFixed(FIXER_RATES.Rates.DOP*ethBtcPrice, 6)
			eth.Rates.DZD = toFixed(FIXER_RATES.Rates.DZD*ethBtcPrice, 6)
			eth.Rates.EGP = toFixed(FIXER_RATES.Rates.EGP*ethBtcPrice, 6)
			eth.Rates.ERN = toFixed(FIXER_RATES.Rates.ERN*ethBtcPrice, 6)
			eth.Rates.ETB = toFixed(FIXER_RATES.Rates.ETB*ethBtcPrice, 6)
			eth.Rates.EUR = toFixed(FIXER_RATES.Rates.EUR*ethBtcPrice, 6)
			eth.Rates.FJD = toFixed(FIXER_RATES.Rates.FJD*ethBtcPrice, 6)
			eth.Rates.FKP = toFixed(FIXER_RATES.Rates.FKP*ethBtcPrice, 6)
			eth.Rates.GBP = toFixed(FIXER_RATES.Rates.GBP*ethBtcPrice, 6)
			eth.Rates.GEL = toFixed(FIXER_RATES.Rates.GEL*ethBtcPrice, 6)
			eth.Rates.GGP = toFixed(FIXER_RATES.Rates.GGP*ethBtcPrice, 6)
			eth.Rates.GHS = toFixed(FIXER_RATES.Rates.GHS*ethBtcPrice, 6)
			eth.Rates.GIP = toFixed(FIXER_RATES.Rates.GIP*ethBtcPrice, 6)
			eth.Rates.GMD = toFixed(FIXER_RATES.Rates.GMD*ethBtcPrice, 6)
			eth.Rates.GNF = toFixed(FIXER_RATES.Rates.GNF*ethBtcPrice, 6)
			eth.Rates.GTQ = toFixed(FIXER_RATES.Rates.GTQ*ethBtcPrice, 6)
			eth.Rates.GYD = toFixed(FIXER_RATES.Rates.GYD*ethBtcPrice, 6)
			eth.Rates.HKD = toFixed(FIXER_RATES.Rates.HKD*ethBtcPrice, 6)
			eth.Rates.HNL = toFixed(FIXER_RATES.Rates.HNL*ethBtcPrice, 6)
			eth.Rates.HRK = toFixed(FIXER_RATES.Rates.HRK*ethBtcPrice, 6)
			eth.Rates.HTG = toFixed(FIXER_RATES.Rates.HTG*ethBtcPrice, 6)
			eth.Rates.HUF = toFixed(FIXER_RATES.Rates.HUF*ethBtcPrice, 6)
			eth.Rates.IDR = toFixed(FIXER_RATES.Rates.IDR*ethBtcPrice, 6)
			eth.Rates.ILS = toFixed(FIXER_RATES.Rates.ILS*ethBtcPrice, 6)
			eth.Rates.IMP = toFixed(FIXER_RATES.Rates.IMP*ethBtcPrice, 6)
			eth.Rates.INR = toFixed(FIXER_RATES.Rates.INR*ethBtcPrice, 6)
			eth.Rates.IQD = toFixed(FIXER_RATES.Rates.IQD*ethBtcPrice, 6)
			eth.Rates.IRR = toFixed(FIXER_RATES.Rates.IRR*ethBtcPrice, 6)
			eth.Rates.ISK = toFixed(FIXER_RATES.Rates.ISK*ethBtcPrice, 6)
			eth.Rates.JEP = toFixed(FIXER_RATES.Rates.JEP*ethBtcPrice, 6)
			eth.Rates.JMD = toFixed(FIXER_RATES.Rates.JMD*ethBtcPrice, 6)
			eth.Rates.JOD = toFixed(FIXER_RATES.Rates.JOD*ethBtcPrice, 6)
			eth.Rates.JPY = toFixed(FIXER_RATES.Rates.JPY*ethBtcPrice, 6)
			eth.Rates.KES = toFixed(FIXER_RATES.Rates.KES*ethBtcPrice, 6)
			eth.Rates.KGS = toFixed(FIXER_RATES.Rates.KGS*ethBtcPrice, 6)
			eth.Rates.KHR = toFixed(FIXER_RATES.Rates.KHR*ethBtcPrice, 6)
			eth.Rates.KMF = toFixed(FIXER_RATES.Rates.KMF*ethBtcPrice, 6)
			eth.Rates.KPW = toFixed(FIXER_RATES.Rates.KPW*ethBtcPrice, 6)
			eth.Rates.KRW = toFixed(FIXER_RATES.Rates.KRW*ethBtcPrice, 6)
			eth.Rates.KWD = toFixed(FIXER_RATES.Rates.KWD*ethBtcPrice, 6)
			eth.Rates.KYD = toFixed(FIXER_RATES.Rates.KYD*ethBtcPrice, 6)
			eth.Rates.KZT = toFixed(FIXER_RATES.Rates.KZT*ethBtcPrice, 6)
			eth.Rates.LAK = toFixed(FIXER_RATES.Rates.LAK*ethBtcPrice, 6)
			eth.Rates.LBP = toFixed(FIXER_RATES.Rates.LBP*ethBtcPrice, 6)
			eth.Rates.LKR = toFixed(FIXER_RATES.Rates.LKR*ethBtcPrice, 6)
			eth.Rates.LRD = toFixed(FIXER_RATES.Rates.LRD*ethBtcPrice, 6)
			eth.Rates.LSL = toFixed(FIXER_RATES.Rates.LSL*ethBtcPrice, 6)
			eth.Rates.LTL = toFixed(FIXER_RATES.Rates.LTL*ethBtcPrice, 6)
			eth.Rates.LVL = toFixed(FIXER_RATES.Rates.LVL*ethBtcPrice, 6)
			eth.Rates.LYD = toFixed(FIXER_RATES.Rates.LYD*ethBtcPrice, 6)
			eth.Rates.MAD = toFixed(FIXER_RATES.Rates.MAD*ethBtcPrice, 6)
			eth.Rates.MDL = toFixed(FIXER_RATES.Rates.MDL*ethBtcPrice, 6)
			eth.Rates.MGA = toFixed(FIXER_RATES.Rates.MGA*ethBtcPrice, 6)
			eth.Rates.MKD = toFixed(FIXER_RATES.Rates.MKD*ethBtcPrice, 6)
			eth.Rates.MMK = toFixed(FIXER_RATES.Rates.MMK*ethBtcPrice, 6)
			eth.Rates.MNT = toFixed(FIXER_RATES.Rates.MNT*ethBtcPrice, 6)
			eth.Rates.MOP = toFixed(FIXER_RATES.Rates.MOP*ethBtcPrice, 6)
			eth.Rates.MRO = toFixed(FIXER_RATES.Rates.MRO*ethBtcPrice, 6)
			eth.Rates.MUR = toFixed(FIXER_RATES.Rates.MUR*ethBtcPrice, 6)
			eth.Rates.MVR = toFixed(FIXER_RATES.Rates.MVR*ethBtcPrice, 6)
			eth.Rates.MWK = toFixed(FIXER_RATES.Rates.MWK*ethBtcPrice, 6)
			eth.Rates.MXN = toFixed(FIXER_RATES.Rates.MXN*ethBtcPrice, 6)
			eth.Rates.MYR = toFixed(FIXER_RATES.Rates.MYR*ethBtcPrice, 6)
			eth.Rates.MZN = toFixed(FIXER_RATES.Rates.MZN*ethBtcPrice, 6)
			eth.Rates.NAD = toFixed(FIXER_RATES.Rates.NAD*ethBtcPrice, 6)
			eth.Rates.NGN = toFixed(FIXER_RATES.Rates.NGN*ethBtcPrice, 6)
			eth.Rates.NIO = toFixed(FIXER_RATES.Rates.NIO*ethBtcPrice, 6)
			eth.Rates.NOK = toFixed(FIXER_RATES.Rates.NOK*ethBtcPrice, 6)
			eth.Rates.NPR = toFixed(FIXER_RATES.Rates.NPR*ethBtcPrice, 6)
			eth.Rates.NZD = toFixed(FIXER_RATES.Rates.NZD*ethBtcPrice, 6)
			eth.Rates.OMR = toFixed(FIXER_RATES.Rates.OMR*ethBtcPrice, 6)
			eth.Rates.PAB = toFixed(FIXER_RATES.Rates.PAB*ethBtcPrice, 6)
			eth.Rates.PEN = toFixed(FIXER_RATES.Rates.PEN*ethBtcPrice, 6)
			eth.Rates.PGK = toFixed(FIXER_RATES.Rates.PGK*ethBtcPrice, 6)
			eth.Rates.PHP = toFixed(FIXER_RATES.Rates.PHP*ethBtcPrice, 6)
			eth.Rates.PKR = toFixed(FIXER_RATES.Rates.PKR*ethBtcPrice, 6)
			eth.Rates.PLN = toFixed(FIXER_RATES.Rates.PLN*ethBtcPrice, 6)
			eth.Rates.PYG = toFixed(FIXER_RATES.Rates.PYG*ethBtcPrice, 6)
			eth.Rates.QAR = toFixed(FIXER_RATES.Rates.QAR*ethBtcPrice, 6)
			eth.Rates.RON = toFixed(FIXER_RATES.Rates.RON*ethBtcPrice, 6)
			eth.Rates.RSD = toFixed(FIXER_RATES.Rates.RSD*ethBtcPrice, 6)
			eth.Rates.RUB = toFixed(FIXER_RATES.Rates.RUB*ethBtcPrice, 6)
			eth.Rates.RWF = toFixed(FIXER_RATES.Rates.RWF*ethBtcPrice, 6)
			eth.Rates.SAR = toFixed(FIXER_RATES.Rates.SAR*ethBtcPrice, 6)
			eth.Rates.SBD = toFixed(FIXER_RATES.Rates.SBD*ethBtcPrice, 6)
			eth.Rates.SCR = toFixed(FIXER_RATES.Rates.SCR*ethBtcPrice, 6)
			eth.Rates.SDG = toFixed(FIXER_RATES.Rates.SDG*ethBtcPrice, 6)
			eth.Rates.SEK = toFixed(FIXER_RATES.Rates.SEK*ethBtcPrice, 6)
			eth.Rates.SGD = toFixed(FIXER_RATES.Rates.SGD*ethBtcPrice, 6)
			eth.Rates.SHP = toFixed(FIXER_RATES.Rates.SHP*ethBtcPrice, 6)
			eth.Rates.SLL = toFixed(FIXER_RATES.Rates.SLL*ethBtcPrice, 6)
			eth.Rates.SOS = toFixed(FIXER_RATES.Rates.SOS*ethBtcPrice, 6)
			eth.Rates.SRD = toFixed(FIXER_RATES.Rates.SRD*ethBtcPrice, 6)
			eth.Rates.STD = toFixed(FIXER_RATES.Rates.STD*ethBtcPrice, 6)
			eth.Rates.SVC = toFixed(FIXER_RATES.Rates.SVC*ethBtcPrice, 6)
			eth.Rates.SYP = toFixed(FIXER_RATES.Rates.SYP*ethBtcPrice, 6)
			eth.Rates.SZL = toFixed(FIXER_RATES.Rates.SZL*ethBtcPrice, 6)
			eth.Rates.THB = toFixed(FIXER_RATES.Rates.THB*ethBtcPrice, 6)
			eth.Rates.TJS = toFixed(FIXER_RATES.Rates.TJS*ethBtcPrice, 6)
			eth.Rates.TMT = toFixed(FIXER_RATES.Rates.TMT*ethBtcPrice, 6)
			eth.Rates.TND = toFixed(FIXER_RATES.Rates.TND*ethBtcPrice, 6)
			eth.Rates.TOP = toFixed(FIXER_RATES.Rates.TOP*ethBtcPrice, 6)
			eth.Rates.TRY = toFixed(FIXER_RATES.Rates.TRY*ethBtcPrice, 6)
			eth.Rates.TTD = toFixed(FIXER_RATES.Rates.TTD*ethBtcPrice, 6)
			eth.Rates.TWD = toFixed(FIXER_RATES.Rates.TWD*ethBtcPrice, 6)
			eth.Rates.TZS = toFixed(FIXER_RATES.Rates.TZS*ethBtcPrice, 6)
			eth.Rates.UAH = toFixed(FIXER_RATES.Rates.UAH*ethBtcPrice, 6)
			eth.Rates.UGX = toFixed(FIXER_RATES.Rates.UGX*ethBtcPrice, 6)
			eth.Rates.USD = toFixed(ethUSDPrice, 6)
			eth.Rates.UYU = toFixed(FIXER_RATES.Rates.UYU*ethBtcPrice, 6)
			eth.Rates.UZS = toFixed(FIXER_RATES.Rates.UZS*ethBtcPrice, 6)
			eth.Rates.VEF = toFixed(FIXER_RATES.Rates.VEF*ethBtcPrice, 6)
			eth.Rates.VND = toFixed(FIXER_RATES.Rates.VND*ethBtcPrice, 6)
			eth.Rates.VUV = toFixed(FIXER_RATES.Rates.VUV*ethBtcPrice, 6)
			eth.Rates.WST = toFixed(FIXER_RATES.Rates.WST*ethBtcPrice, 6)
			eth.Rates.XAF = toFixed(FIXER_RATES.Rates.XAF*ethBtcPrice, 6)
			eth.Rates.XAG = toFixed(FIXER_RATES.Rates.XAG*ethBtcPrice, 6)
			eth.Rates.XAU = toFixed(FIXER_RATES.Rates.XAU*ethBtcPrice, 6)
			eth.Rates.XCD = toFixed(FIXER_RATES.Rates.XCD*ethBtcPrice, 6)
			eth.Rates.XDR = toFixed(FIXER_RATES.Rates.XDR*ethBtcPrice, 6)
			eth.Rates.XOF = toFixed(FIXER_RATES.Rates.XOF*ethBtcPrice, 6)
			eth.Rates.XPF = toFixed(FIXER_RATES.Rates.XPF*ethBtcPrice, 6)
			eth.Rates.YER = toFixed(FIXER_RATES.Rates.YER*ethBtcPrice, 6)
			eth.Rates.ZAR = toFixed(FIXER_RATES.Rates.ZAR*ethBtcPrice, 6)
			eth.Rates.ZMK = toFixed(FIXER_RATES.Rates.ZMK*ethBtcPrice, 6)
			eth.Rates.ZMW = toFixed(FIXER_RATES.Rates.ZMW*ethBtcPrice, 6)
			eth.Rates.ZWL = toFixed(FIXER_RATES.Rates.ZWL*ethBtcPrice, 6)

			ETH_BTC_BINANCE_RATES = eth

			// b, _ := json.Marshal(arrr)
			// fmt.Println(string(b))
		}

		sleepSeconds := BINANCE_SECONDS
		log.Printf("Updated ETH Rates from Binance for ETH/BTC pair. Will update again in %v seconds...\n", sleepSeconds)
		time.Sleep(time.Duration(sleepSeconds) * time.Second)
	}
}

func DotBtcBinanceAPI(wg *sync.WaitGroup) {
	defer func() {
		if r := recover(); r != nil {
			utils.Log.Println("Recovered in DotBtcBinanceAPI", r)
		}
	}()
	updateMarketsAvailable("binance", "DOT-BTC", wg)
	// Forever loop to keep fetching rates every N seconds
	for {
		url := "https://api.binance.com/api/v3/trades?symbol=DOTBTC"
		params := ``
		result, err := RPCResultMap(url, params)
		if err != nil {
			log.Printf("Got error fetching Binance DOT/BTC rates: %v\n", err)
		}
		// fmt.Println(result)

		resultType := fmt.Sprintf("%T", result)
		if resultType != "[]interface {}" {
			fmt.Println("type is not []interface {}")
			fmt.Println("resultType value:", resultType)
			fmt.Printf("xTyle type: %T\n", resultType)
		} else {
			dotBtcPrice, _ := strconv.ParseFloat(result.([]interface{})[0].(map[string]interface{})["price"].(string), 64)
			dotUSDPrice := dotBtcPrice * BTC_RATES.Rates.USD
			// fmt.Println("==========================")
			// fmt.Printf("DOT Price (BTC): %.8f\n", dotBtcPrice)
			// fmt.Printf("DOT Price (USD): %.6f\n", dotUSDPrice)
			// fmt.Println("==========================")
			var dot ConversionRates
			dot.Timestamp = int64(result.([]interface{})[0].(map[string]interface{})["time"].(float64))
			dot.Base = "DOT/BTC"
			dot.Market = "Binance"
			dot.Rates.AED = toFixed(FIXER_RATES.Rates.AED*dotBtcPrice, 6)
			dot.Rates.AFN = toFixed(FIXER_RATES.Rates.AFN*dotBtcPrice, 6)
			dot.Rates.ALL = toFixed(FIXER_RATES.Rates.ALL*dotBtcPrice, 6)
			dot.Rates.AMD = toFixed(FIXER_RATES.Rates.AMD*dotBtcPrice, 6)
			dot.Rates.ANG = toFixed(FIXER_RATES.Rates.ANG*dotBtcPrice, 6)
			dot.Rates.AOA = toFixed(FIXER_RATES.Rates.AOA*dotBtcPrice, 6)
			dot.Rates.ARS = toFixed(FIXER_RATES.Rates.ARS*dotBtcPrice, 6)
			dot.Rates.AUD = toFixed(FIXER_RATES.Rates.AUD*dotBtcPrice, 6)
			dot.Rates.AWG = toFixed(FIXER_RATES.Rates.AWG*dotBtcPrice, 6)
			dot.Rates.AZN = toFixed(FIXER_RATES.Rates.AZN*dotBtcPrice, 6)
			dot.Rates.BAM = toFixed(FIXER_RATES.Rates.BAM*dotBtcPrice, 6)
			dot.Rates.BBD = toFixed(FIXER_RATES.Rates.BBD*dotBtcPrice, 6)
			dot.Rates.BDT = toFixed(FIXER_RATES.Rates.BDT*dotBtcPrice, 6)
			dot.Rates.BGN = toFixed(FIXER_RATES.Rates.BGN*dotBtcPrice, 6)
			dot.Rates.BHD = toFixed(FIXER_RATES.Rates.BHD*dotBtcPrice, 6)
			dot.Rates.BIF = toFixed(FIXER_RATES.Rates.BIF*dotBtcPrice, 6)
			dot.Rates.BMD = toFixed(dotUSDPrice, 6)
			dot.Rates.BND = toFixed(FIXER_RATES.Rates.BND*dotBtcPrice, 6)
			dot.Rates.BOB = toFixed(FIXER_RATES.Rates.BOB*dotBtcPrice, 6)
			dot.Rates.BRL = toFixed(FIXER_RATES.Rates.BRL*dotBtcPrice, 6)
			dot.Rates.BSD = toFixed(FIXER_RATES.Rates.BSD*dotBtcPrice, 6)
			dot.Rates.BTC = toFixed(dotBtcPrice, 8)
			dot.Rates.BTN = toFixed(FIXER_RATES.Rates.BTN*dotBtcPrice, 6)
			dot.Rates.BWP = toFixed(FIXER_RATES.Rates.BWP*dotBtcPrice, 6)
			dot.Rates.BYN = toFixed(FIXER_RATES.Rates.BYN*dotBtcPrice, 6)
			dot.Rates.BYR = toFixed(FIXER_RATES.Rates.BYR*dotBtcPrice, 6)
			dot.Rates.BZD = toFixed(FIXER_RATES.Rates.BZD*dotBtcPrice, 6)
			dot.Rates.CAD = toFixed(FIXER_RATES.Rates.CAD*dotBtcPrice, 6)
			dot.Rates.CDF = toFixed(FIXER_RATES.Rates.CDF*dotBtcPrice, 6)
			dot.Rates.CHF = toFixed(FIXER_RATES.Rates.CHF*dotBtcPrice, 6)
			dot.Rates.CLF = toFixed(FIXER_RATES.Rates.CLF*dotBtcPrice, 6)
			dot.Rates.CLP = toFixed(FIXER_RATES.Rates.CLP*dotBtcPrice, 6)
			dot.Rates.CNY = toFixed(FIXER_RATES.Rates.CNY*dotBtcPrice, 6)
			dot.Rates.COP = toFixed(FIXER_RATES.Rates.COP*dotBtcPrice, 6)
			dot.Rates.CRC = toFixed(FIXER_RATES.Rates.CRC*dotBtcPrice, 6)
			dot.Rates.CUC = toFixed(dotUSDPrice, 6)
			dot.Rates.CUP = toFixed(FIXER_RATES.Rates.CUP*dotBtcPrice, 6)
			dot.Rates.CVE = toFixed(FIXER_RATES.Rates.CVE*dotBtcPrice, 6)
			dot.Rates.CZK = toFixed(FIXER_RATES.Rates.CZK*dotBtcPrice, 6)
			dot.Rates.DJF = toFixed(FIXER_RATES.Rates.DJF*dotBtcPrice, 6)
			dot.Rates.DKK = toFixed(FIXER_RATES.Rates.DKK*dotBtcPrice, 6)
			dot.Rates.DOP = toFixed(FIXER_RATES.Rates.DOP*dotBtcPrice, 6)
			dot.Rates.DZD = toFixed(FIXER_RATES.Rates.DZD*dotBtcPrice, 6)
			dot.Rates.EGP = toFixed(FIXER_RATES.Rates.EGP*dotBtcPrice, 6)
			dot.Rates.ERN = toFixed(FIXER_RATES.Rates.ERN*dotBtcPrice, 6)
			dot.Rates.ETB = toFixed(FIXER_RATES.Rates.ETB*dotBtcPrice, 6)
			dot.Rates.EUR = toFixed(FIXER_RATES.Rates.EUR*dotBtcPrice, 6)
			dot.Rates.FJD = toFixed(FIXER_RATES.Rates.FJD*dotBtcPrice, 6)
			dot.Rates.FKP = toFixed(FIXER_RATES.Rates.FKP*dotBtcPrice, 6)
			dot.Rates.GBP = toFixed(FIXER_RATES.Rates.GBP*dotBtcPrice, 6)
			dot.Rates.GEL = toFixed(FIXER_RATES.Rates.GEL*dotBtcPrice, 6)
			dot.Rates.GGP = toFixed(FIXER_RATES.Rates.GGP*dotBtcPrice, 6)
			dot.Rates.GHS = toFixed(FIXER_RATES.Rates.GHS*dotBtcPrice, 6)
			dot.Rates.GIP = toFixed(FIXER_RATES.Rates.GIP*dotBtcPrice, 6)
			dot.Rates.GMD = toFixed(FIXER_RATES.Rates.GMD*dotBtcPrice, 6)
			dot.Rates.GNF = toFixed(FIXER_RATES.Rates.GNF*dotBtcPrice, 6)
			dot.Rates.GTQ = toFixed(FIXER_RATES.Rates.GTQ*dotBtcPrice, 6)
			dot.Rates.GYD = toFixed(FIXER_RATES.Rates.GYD*dotBtcPrice, 6)
			dot.Rates.HKD = toFixed(FIXER_RATES.Rates.HKD*dotBtcPrice, 6)
			dot.Rates.HNL = toFixed(FIXER_RATES.Rates.HNL*dotBtcPrice, 6)
			dot.Rates.HRK = toFixed(FIXER_RATES.Rates.HRK*dotBtcPrice, 6)
			dot.Rates.HTG = toFixed(FIXER_RATES.Rates.HTG*dotBtcPrice, 6)
			dot.Rates.HUF = toFixed(FIXER_RATES.Rates.HUF*dotBtcPrice, 6)
			dot.Rates.IDR = toFixed(FIXER_RATES.Rates.IDR*dotBtcPrice, 6)
			dot.Rates.ILS = toFixed(FIXER_RATES.Rates.ILS*dotBtcPrice, 6)
			dot.Rates.IMP = toFixed(FIXER_RATES.Rates.IMP*dotBtcPrice, 6)
			dot.Rates.INR = toFixed(FIXER_RATES.Rates.INR*dotBtcPrice, 6)
			dot.Rates.IQD = toFixed(FIXER_RATES.Rates.IQD*dotBtcPrice, 6)
			dot.Rates.IRR = toFixed(FIXER_RATES.Rates.IRR*dotBtcPrice, 6)
			dot.Rates.ISK = toFixed(FIXER_RATES.Rates.ISK*dotBtcPrice, 6)
			dot.Rates.JEP = toFixed(FIXER_RATES.Rates.JEP*dotBtcPrice, 6)
			dot.Rates.JMD = toFixed(FIXER_RATES.Rates.JMD*dotBtcPrice, 6)
			dot.Rates.JOD = toFixed(FIXER_RATES.Rates.JOD*dotBtcPrice, 6)
			dot.Rates.JPY = toFixed(FIXER_RATES.Rates.JPY*dotBtcPrice, 6)
			dot.Rates.KES = toFixed(FIXER_RATES.Rates.KES*dotBtcPrice, 6)
			dot.Rates.KGS = toFixed(FIXER_RATES.Rates.KGS*dotBtcPrice, 6)
			dot.Rates.KHR = toFixed(FIXER_RATES.Rates.KHR*dotBtcPrice, 6)
			dot.Rates.KMF = toFixed(FIXER_RATES.Rates.KMF*dotBtcPrice, 6)
			dot.Rates.KPW = toFixed(FIXER_RATES.Rates.KPW*dotBtcPrice, 6)
			dot.Rates.KRW = toFixed(FIXER_RATES.Rates.KRW*dotBtcPrice, 6)
			dot.Rates.KWD = toFixed(FIXER_RATES.Rates.KWD*dotBtcPrice, 6)
			dot.Rates.KYD = toFixed(FIXER_RATES.Rates.KYD*dotBtcPrice, 6)
			dot.Rates.KZT = toFixed(FIXER_RATES.Rates.KZT*dotBtcPrice, 6)
			dot.Rates.LAK = toFixed(FIXER_RATES.Rates.LAK*dotBtcPrice, 6)
			dot.Rates.LBP = toFixed(FIXER_RATES.Rates.LBP*dotBtcPrice, 6)
			dot.Rates.LKR = toFixed(FIXER_RATES.Rates.LKR*dotBtcPrice, 6)
			dot.Rates.LRD = toFixed(FIXER_RATES.Rates.LRD*dotBtcPrice, 6)
			dot.Rates.LSL = toFixed(FIXER_RATES.Rates.LSL*dotBtcPrice, 6)
			dot.Rates.LTL = toFixed(FIXER_RATES.Rates.LTL*dotBtcPrice, 6)
			dot.Rates.LVL = toFixed(FIXER_RATES.Rates.LVL*dotBtcPrice, 6)
			dot.Rates.LYD = toFixed(FIXER_RATES.Rates.LYD*dotBtcPrice, 6)
			dot.Rates.MAD = toFixed(FIXER_RATES.Rates.MAD*dotBtcPrice, 6)
			dot.Rates.MDL = toFixed(FIXER_RATES.Rates.MDL*dotBtcPrice, 6)
			dot.Rates.MGA = toFixed(FIXER_RATES.Rates.MGA*dotBtcPrice, 6)
			dot.Rates.MKD = toFixed(FIXER_RATES.Rates.MKD*dotBtcPrice, 6)
			dot.Rates.MMK = toFixed(FIXER_RATES.Rates.MMK*dotBtcPrice, 6)
			dot.Rates.MNT = toFixed(FIXER_RATES.Rates.MNT*dotBtcPrice, 6)
			dot.Rates.MOP = toFixed(FIXER_RATES.Rates.MOP*dotBtcPrice, 6)
			dot.Rates.MRO = toFixed(FIXER_RATES.Rates.MRO*dotBtcPrice, 6)
			dot.Rates.MUR = toFixed(FIXER_RATES.Rates.MUR*dotBtcPrice, 6)
			dot.Rates.MVR = toFixed(FIXER_RATES.Rates.MVR*dotBtcPrice, 6)
			dot.Rates.MWK = toFixed(FIXER_RATES.Rates.MWK*dotBtcPrice, 6)
			dot.Rates.MXN = toFixed(FIXER_RATES.Rates.MXN*dotBtcPrice, 6)
			dot.Rates.MYR = toFixed(FIXER_RATES.Rates.MYR*dotBtcPrice, 6)
			dot.Rates.MZN = toFixed(FIXER_RATES.Rates.MZN*dotBtcPrice, 6)
			dot.Rates.NAD = toFixed(FIXER_RATES.Rates.NAD*dotBtcPrice, 6)
			dot.Rates.NGN = toFixed(FIXER_RATES.Rates.NGN*dotBtcPrice, 6)
			dot.Rates.NIO = toFixed(FIXER_RATES.Rates.NIO*dotBtcPrice, 6)
			dot.Rates.NOK = toFixed(FIXER_RATES.Rates.NOK*dotBtcPrice, 6)
			dot.Rates.NPR = toFixed(FIXER_RATES.Rates.NPR*dotBtcPrice, 6)
			dot.Rates.NZD = toFixed(FIXER_RATES.Rates.NZD*dotBtcPrice, 6)
			dot.Rates.OMR = toFixed(FIXER_RATES.Rates.OMR*dotBtcPrice, 6)
			dot.Rates.PAB = toFixed(FIXER_RATES.Rates.PAB*dotBtcPrice, 6)
			dot.Rates.PEN = toFixed(FIXER_RATES.Rates.PEN*dotBtcPrice, 6)
			dot.Rates.PGK = toFixed(FIXER_RATES.Rates.PGK*dotBtcPrice, 6)
			dot.Rates.PHP = toFixed(FIXER_RATES.Rates.PHP*dotBtcPrice, 6)
			dot.Rates.PKR = toFixed(FIXER_RATES.Rates.PKR*dotBtcPrice, 6)
			dot.Rates.PLN = toFixed(FIXER_RATES.Rates.PLN*dotBtcPrice, 6)
			dot.Rates.PYG = toFixed(FIXER_RATES.Rates.PYG*dotBtcPrice, 6)
			dot.Rates.QAR = toFixed(FIXER_RATES.Rates.QAR*dotBtcPrice, 6)
			dot.Rates.RON = toFixed(FIXER_RATES.Rates.RON*dotBtcPrice, 6)
			dot.Rates.RSD = toFixed(FIXER_RATES.Rates.RSD*dotBtcPrice, 6)
			dot.Rates.RUB = toFixed(FIXER_RATES.Rates.RUB*dotBtcPrice, 6)
			dot.Rates.RWF = toFixed(FIXER_RATES.Rates.RWF*dotBtcPrice, 6)
			dot.Rates.SAR = toFixed(FIXER_RATES.Rates.SAR*dotBtcPrice, 6)
			dot.Rates.SBD = toFixed(FIXER_RATES.Rates.SBD*dotBtcPrice, 6)
			dot.Rates.SCR = toFixed(FIXER_RATES.Rates.SCR*dotBtcPrice, 6)
			dot.Rates.SDG = toFixed(FIXER_RATES.Rates.SDG*dotBtcPrice, 6)
			dot.Rates.SEK = toFixed(FIXER_RATES.Rates.SEK*dotBtcPrice, 6)
			dot.Rates.SGD = toFixed(FIXER_RATES.Rates.SGD*dotBtcPrice, 6)
			dot.Rates.SHP = toFixed(FIXER_RATES.Rates.SHP*dotBtcPrice, 6)
			dot.Rates.SLL = toFixed(FIXER_RATES.Rates.SLL*dotBtcPrice, 6)
			dot.Rates.SOS = toFixed(FIXER_RATES.Rates.SOS*dotBtcPrice, 6)
			dot.Rates.SRD = toFixed(FIXER_RATES.Rates.SRD*dotBtcPrice, 6)
			dot.Rates.STD = toFixed(FIXER_RATES.Rates.STD*dotBtcPrice, 6)
			dot.Rates.SVC = toFixed(FIXER_RATES.Rates.SVC*dotBtcPrice, 6)
			dot.Rates.SYP = toFixed(FIXER_RATES.Rates.SYP*dotBtcPrice, 6)
			dot.Rates.SZL = toFixed(FIXER_RATES.Rates.SZL*dotBtcPrice, 6)
			dot.Rates.THB = toFixed(FIXER_RATES.Rates.THB*dotBtcPrice, 6)
			dot.Rates.TJS = toFixed(FIXER_RATES.Rates.TJS*dotBtcPrice, 6)
			dot.Rates.TMT = toFixed(FIXER_RATES.Rates.TMT*dotBtcPrice, 6)
			dot.Rates.TND = toFixed(FIXER_RATES.Rates.TND*dotBtcPrice, 6)
			dot.Rates.TOP = toFixed(FIXER_RATES.Rates.TOP*dotBtcPrice, 6)
			dot.Rates.TRY = toFixed(FIXER_RATES.Rates.TRY*dotBtcPrice, 6)
			dot.Rates.TTD = toFixed(FIXER_RATES.Rates.TTD*dotBtcPrice, 6)
			dot.Rates.TWD = toFixed(FIXER_RATES.Rates.TWD*dotBtcPrice, 6)
			dot.Rates.TZS = toFixed(FIXER_RATES.Rates.TZS*dotBtcPrice, 6)
			dot.Rates.UAH = toFixed(FIXER_RATES.Rates.UAH*dotBtcPrice, 6)
			dot.Rates.UGX = toFixed(FIXER_RATES.Rates.UGX*dotBtcPrice, 6)
			dot.Rates.USD = toFixed(dotUSDPrice, 6)
			dot.Rates.UYU = toFixed(FIXER_RATES.Rates.UYU*dotBtcPrice, 6)
			dot.Rates.UZS = toFixed(FIXER_RATES.Rates.UZS*dotBtcPrice, 6)
			dot.Rates.VEF = toFixed(FIXER_RATES.Rates.VEF*dotBtcPrice, 6)
			dot.Rates.VND = toFixed(FIXER_RATES.Rates.VND*dotBtcPrice, 6)
			dot.Rates.VUV = toFixed(FIXER_RATES.Rates.VUV*dotBtcPrice, 6)
			dot.Rates.WST = toFixed(FIXER_RATES.Rates.WST*dotBtcPrice, 6)
			dot.Rates.XAF = toFixed(FIXER_RATES.Rates.XAF*dotBtcPrice, 6)
			dot.Rates.XAG = toFixed(FIXER_RATES.Rates.XAG*dotBtcPrice, 6)
			dot.Rates.XAU = toFixed(FIXER_RATES.Rates.XAU*dotBtcPrice, 6)
			dot.Rates.XCD = toFixed(FIXER_RATES.Rates.XCD*dotBtcPrice, 6)
			dot.Rates.XDR = toFixed(FIXER_RATES.Rates.XDR*dotBtcPrice, 6)
			dot.Rates.XOF = toFixed(FIXER_RATES.Rates.XOF*dotBtcPrice, 6)
			dot.Rates.XPF = toFixed(FIXER_RATES.Rates.XPF*dotBtcPrice, 6)
			dot.Rates.YER = toFixed(FIXER_RATES.Rates.YER*dotBtcPrice, 6)
			dot.Rates.ZAR = toFixed(FIXER_RATES.Rates.ZAR*dotBtcPrice, 6)
			dot.Rates.ZMK = toFixed(FIXER_RATES.Rates.ZMK*dotBtcPrice, 6)
			dot.Rates.ZMW = toFixed(FIXER_RATES.Rates.ZMW*dotBtcPrice, 6)
			dot.Rates.ZWL = toFixed(FIXER_RATES.Rates.ZWL*dotBtcPrice, 6)

			DOT_BTC_BINANCE_RATES = dot

			// b, _ := json.Marshal(arrr)
			// fmt.Println(string(b))
		}

		sleepSeconds := BINANCE_SECONDS
		log.Printf("Updated DOT Rates from Binance for DOT/BTC pair. Will update again in %v seconds...\n", sleepSeconds)
		time.Sleep(time.Duration(sleepSeconds) * time.Second)
	}
}
